version: 0.2

phases:
  pre_build:
    commands:
      - docker login -u $dockerhub_username -p $dockerhub_password
      - docker-compose up -d --scale chrome=1
  build:
    commands:
      - mvn test
  post_build:
    commands:
      - docker-compose down
reports:
  Selenium:
    file-format: CucumberJson
    files:
      - target/json/output.json
